version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  producer:
    image: rubyan/redis-producer
    build:
      context: .
      dockerfile: Dockerfile.producer
    environment:
      - PYTHONUNBUFFERED=1

  consumer:
    image: rubyan/redis-consumer
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      - PYTHONUNBUFFERED=1

  observer:
    image: rubyan/redis-observer
    build:
      context: .
      dockerfile: Dockerfile.observer
    environment:
      - PYTHONUNBUFFERED=1

