version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

  producer:
    image: redis-producer
    build:
      context: .
      dockerfile: Dockerfile.producer
    environment:
      - PYTHONUNBUFFERED=1

  consumer:
    image: redis-consumer 
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      - PYTHONUNBUFFERED=1

  observer:
    image: redis-observer
    build:
      context: .
      dockerfile: Dockerfile.observer
    environment:
      - PYTHONUNBUFFERED=1


