apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: producer
    spec:
      containers:
      - image: rubyan/producer:1.2
        name: producer
        envFrom:
        - configMapRef:
            name: producer 
        resources: {}
status: {}
