apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: producer
  name: producer
spec:
  containers:
  - image: rubyan/producer:1.1
    name: producer
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
